controller/controller.py
class login:
    def __init__(self,login = None):
        self.login = login
        pass

    def verify(self, values):
        login = {'Cpf' : values[0], 'Nome' : values[1],'Email' : values[2],'Senha' : values[3], 'Tel' : values[4], 'Ender' : values[5], 'Nasc' : values[6]}
        return login
        ...

main.py
from flask import Flask, render_template, url_for
from routes.client import client_route
from routes.home import home_route
from routes.product import product_route
from database.database import BancoDeDados

app = Flask(__name__)
db = BancoDeDados()
db.connect()

app.register_blueprint(home_route)
app.register_blueprint(client_route, url_prefix='/client')
app.register_blueprint(product_route, url_prefix='/product')

app.run(debug=True)
db.disconnect()

routes/cart.py
from flask import Flask, Blueprint, render_template, request
from database.database import BancoDeDados

db = BancoDeDados()
cart_route = Blueprint("cart", __name__)

@cart_route.route("/cart", methods=['GET', 'POST'])
def cart():
    
    return render_template("cart.html")

routes/client.py
from flask import Flask, Blueprint, render_template, request
from database.database import BancoDeDados 

db = BancoDeDados()
client_route = Blueprint("client", __name__)

# @client_route.route("/add")
# def add_client():
#     return render_template("form_add_user.html")

@client_route.route("/add", methods=['GET', 'POST'])
def singup():
    if request.method == "POST":
        Nome = request.form['Nome']
        Email = request.form['Email']
        Senha = request.form['Senha']
        Cpf = request.form['Cpf']
        Nasc = f"{request.form['NascA']}-{request.form['NascM']}-{request.form['NascD']}"
        Ender = request.form['Ender']
        Tel = request.form['Tel']
        values = (Cpf,Nome,Email,Senha,Tel,Ender,Nasc)
        db.singup(values)
        return render_template("login.html")
        # print(values)

        ...
    # data = request.json
    # print(data)
    # values = (data)
    # 
    return render_template("form_add_user.html")
    ...

@client_route.route("/login", methods=['GET', 'POST'])
def singin():
        if request.method == "POST":
            Email = request.form['Email']
            Senha = request.form['Senha']
            values = (Email,Senha)
            db.singin(values)
            return render_template("index.html")
        return render_template("login.html")

@client_route.route("/acount")
def acount():
    dt = db.verify()
    if dt != None:
       return render_template("acount.html", dados = dt)
    return render_template("login.html")

routes/home.py
from flask import Flask, Blueprint, render_template

home_route = Blueprint("home", __name__)

@home_route.route('/')
def home():

    return render_template("index.html")

routes/payment.py
from flask import Flask, render_template, Blueprint

pay_route = Blueprint("payment", __name__)

@pay_route.route("/add")
def add_met_pay():
    return render_template('form_add_payment.html')

routes/product.py
from flask import Flask, render_template, Blueprint, request
from database.database import BancoDeDados
db = BancoDeDados()
product_route = Blueprint("product", __name__)

@product_route.route("/add", methods=['GET', 'POST'])
def add_prod():
    if request.method == "POST":
        Cod = request.form['Cod']
        Nome = request.form['Nome']
        Desc = request.form['Desc']
        Preco = request.form['Preco']
        Categ = request.form['Categ']
        Quant = request.form['Quant']
        values = (int(Cod),Nome,Desc,float(Preco),Categ,int(Quant))
        db.addProd(values)
        return render_template("form_add_prod.html")
    return render_template('form_add_prod.html')

@product_route.route('/armazenamento')
def arm():
    return render_template('armazenamento.html')

@product_route.route('/alimentacao')
def alim():
    return render_template('alimentacao.html')

@product_route.route("/gab", methods=['GET', 'POST'])
def gab_card():
    if request.method == "POST":
        values = (1)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('gabinete.html')

@product_route.route("/sata")
def ssd_sata():
    if request.method == "POST":
        values = (2)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('ssd_sata.html')

@product_route.route("/watercooler")
def water_cooler():
    if request.method == "POST":
        values = (3)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('watercooler.html')

@product_route.route("/fonte_for")
def fonte_for():
    if request.method == "POST":
        values = (4)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('fonte.html')

@product_route.route("/ram")
def memory_ram():
    if request.method == "POST":
        values = (5)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('ram.html')

@product_route.route("/mother_board")
def motherboard():
    if request.method == "POST":
        values = (6)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('placa_mae.html')

@product_route.route("/rtx")
def graphicboard():
    if request.method == "POST":
        values = (7)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('placa_video.html')

@product_route.route("/corsair")
def fonte_cor():
    if request.method == "POST":
        values = (8)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('fonte_cor.html')

@product_route.route("/nvme")
def ssd_nvme():
    if request.method == "POST":
        values = (9)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('ssd_nvme.html')

@product_route.route("/amd")
def proc_amd():
    if request.method == "POST":
        values = (10)
        prod = db.returnProd(values)
        if prod == None:
            return render_template("login.html")
        db.addCart(prod)
        return render_template("index.html")
    return render_template('ryzen.html')

templates/alimentacao.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GMG TECH</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body class="gradient-background">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{ url_for('home.home' )}}">GMG TECH</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('client.acount')}}">Minha conta</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" 
                    aria-current="page" href="#">Ofertas do dia</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Produtos
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Todos produtos</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.arm' )}}">Armazenamentos</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.alim' )}}">Fontes de alimentação</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.gab_card')}}">Gabinetes</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.memory_ram')}}">Memórias RAM</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.motherboard')}}">Placas mãe</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.proc_amd')}}">Processadores</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.graphicboard')}}">Placas de vídeo</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.water_cooler')}}">Refrigerações</a></li>
                    </ul>
                </ul>
                <button class="btn btn-outline-success" type="submit"><a href="{{url_for('client.singin')}}"><img src="{{ url_for('static', filename='assets/carrinho.png')}}" alt="Imagem carrinho" width="21px" height="21px"></a></button>
                <form class="d-flex" role="search" style="padding: 5px;">
                  <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Pesquisar" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit"><img src="{{url_for('static', filename='assets/lupa.png')}}" alt="Imagem pesquisa" width="15px" height="15px"></a></button>
                </form>
              </div>
            </div>
          </nav>

          <div class="card-container" style="display: grid;">
            <div class="card" style="width: 18rem; padding: 20px; align-content: center;">
                <a class="link" href="{{url_for('product.fonte_for')}}">
                <img src="{{url_for('static', filename='assets/fonte1.jpeg')}}" class="card-img-top" alt="Fonte">
                <div class="card-body">
                  <h5 class="card-title">Fonte Gamer Fortrek ATX Crusader, 500W, sem cabo, Preto - 76955</h5>
                  <br>
                  <p class="card-text">De R$140,00</p>
                  <p class="card-text-1">Por R$100,00</p>
                </div>
              </a>
              <div class="card" style="width: 18rem; padding: 20px; align-content: center;">
                <a class="link" href="{{url_for('product.fonte_cor')}}">
                <img src="{{url_for('static', filename='assets/fontecorsair1.jpeg')}}" class="card-img-top" alt="Fonte">
                <div class="card-body">
                  <h5 class="card-title">Fonte Corsair RM1000x, 1000W, 80 Plus Gold, Modular, PFC Ativo</h5>
                  <br>
                  <p class="card-text">De R$1993,00</p>
                  <p class="card-text-1">Por R$1295,45</p>
                </div>
              </a>
          </div>
    </body>
</html>

templates/armazenamento.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GMG TECH</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body class="gradient-background">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{ url_for('home.home' )}}">GMG TECH</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('client.acount')}}">Minha conta</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" 
                    aria-current="page" href="#">Ofertas do dia</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Produtos
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Todos produtos</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.arm' )}}">Armazenamentos</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.alim' )}}">Fontes de alimentação</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.gab_card')}}">Gabinetes</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.memory_ram')}}">Memórias RAM</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.motherboard')}}">Placas mãe</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.proc_amd')}}">Processadores</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.graphicboard')}}">Placas de vídeo</a></li>
                      <li><a class="dropdown-item" href="{{ url_for('product.water_cooler')}}">Refrigerações</a></li>
                    </ul>
                </ul>
                <button class="btn btn-outline-success" type="submit"><a href="{{url_for('client.singin')}}"><img src="{{ url_for('static', filename='assets/carrinho.png')}}" alt="Imagem carrinho" width="21px" height="21px"></a></button>
                <form class="d-flex" role="search" style="padding: 5px;">
                  <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Pesquisar" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit"><img src="{{url_for('static', filename='assets/lupa.png')}}" alt="Imagem pesquisa" width="15px" height="15px"></a></button>
                </form>
              </div>
            </div>
          </nav>

          <div class="card-container" style="display: grid;">
            <div class="card" style="width: 18rem; padding: 20px; align-content: center;">
                <a class="link" href="{{url_for('product.ssd_sata')}}">
                <img src="{{url_for('static', filename='assets/ss1.jpeg')}}" class="card-img-top" alt="SSD">
                <div class="card-body">
                  <h5 class="card-title">SSD SATA WD Green, 1TB, 2.5", Leitura: 545MB/s e Gravação: 550MB/s, Preto - WDS100T3G0A</h5>
                  <br>
                  <p class="card-text">De R$560,00</p>
                  <p class="card-text-1">Por R$420,00</p>
                </div>
              </a>
              <div class="card" style="width: 18rem; padding: 20px; align-content: center;">
                <a class="link" href="{{url_for('product.ssd_nvme')}}">
                <img src="{{url_for('static', filename='assets/ssdfury1.jpeg')}}" class="card-img-top" alt="SSD">
                <div class="card-body">
                  <h5 class="card-title">SSD 2 TB Kingston Fury Renegade, M.2 2280 PCIe, NVMe, Leitura: 7300MB/s e Gravação: 7000MB/s, Preto - SFYRD/2000G</h5>
                  <br>
                  <p class="card-text">De R$1530,00</p>
                  <p class="card-text-1">Por R$841,50</p>
                </div>
              </a>
          </div>
    </body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GMG TECH</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body class="gradient-background">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('home.home' )}}">GMG TECH</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('client.acount')}}">Minha conta</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" 
                aria-current="page" href="#">Ofertas do dia</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Produtos
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Todos produtos</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{{ url_for('product.arm' )}}">Armazenamentos</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('product.alim' )}}">Fontes de alimentação</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('product.gab_card' )}}">Gabinetes</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('product.memory_ram' )}}">Memórias RAM</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('product.motherboard' )}}">Placas mãe</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('product.proc_amd' )}}">Processadores</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('product.graphicboard' )}}">Placas de vídeo</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('product.water_cooler' )}}">Refrigerações</a></li>
                </ul>
            </ul>
            <button class="btn btn-outline-success" type="submit"><a href="{{url_for('client.singin')}}"><img src="{{ url_for('static', filename='assets/carrinho.png')}}" alt="Imagem carrinho" width="21px" height="21px"></a></button>
            <form class="d-flex" role="search" style="padding: 5px;">
              <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Pesquisar" aria-label="Search">
              <button class="btn btn-outline-success" type="submit"><img src="{{url_for('static', filename='assets/lupa.png')}}" alt="Imagem pesquisa" width="15px" height="15px"></a></button>
            </form>
          </div>
        </div>
      </nav>

      <div id="carouselExampleFade" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="5000">
            <a href="{{url_for('product.memory_ram')}}">
            <img src="{{url_for('static', filename='assets/1.jpeg')}}" class="d-block w-100" alt="Memória RAM">
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="5000">
            <a href="{{url_for('product.motherboard')}}">
            <img src="{{url_for('static', filename='assets/2.jpeg')}}" class="d-block w-100" alt="Placa Mãe Asus">
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="5000">
            <a href="{{url_for('product.graphicboard')}}">
            <img src="{{url_for('static', filename='assets/3.jpeg')}}" class="d-block w-100" alt="Placa de Vídeo">
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="5000">
            <a href="{{url_for('product.fonte_cor')}}">
            <img src="{{url_for('static', filename='assets/4.jpeg')}}" class="d-block w-100" alt="Fonte Corsair">
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="5000">
            <a href="{{url_for('product.ssd_nvme')}}">
            <img src="{{url_for('static', filename='assets/5.jpeg')}}" class="d-block w-100" alt="SSD kingston">
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="5000">
            <a href="{{url_for('product.proc_amd')}}">
            <img src="{{url_for('static', filename='assets/6.jpeg')}}" class="d-block w-100" alt="Processador AMD">
            </a>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <br>
      <div class="card-container">
        <div class="card" style="width: 18rem; padding: 20px; align-content: center;">
          <a class="link" href="{{url_for('product.gab_card')}}">
          <img src="{{url_for('static', filename='assets/gabinete1.jpeg')}}" class="card-img-top" alt="Gabinete">
          <div class="card-body">
            <h5 class="card-title">Gabinete Gamer Lian Li Dynamic Mini-X O11, PC Tower, ATX, Lateral em Vidro Temperado, Preto - O11DMINI-X</h5>
            <br>
            <p class="card-text">De R$680,00</p>
            <p class="card-text-1">Por R$520,00</p>
          </div>
        </a>
        </div>
        <div class="card" style="width: 18rem; padding: 20px; align-content: center;">
          <a class="link" href="{{url_for('product.ssd_sata')}}">
          <img src="{{url_for('static', filename='assets/ss1.jpeg')}}" class="card-img-top" alt="SSD">
          <div class="card-body">
            <h5 class="card-title">SSD SATA WD Green, 1TB, 2.5", Leitura: 545MB/s e Gravação: 550MB/s, Preto - WDS100T3G0A</h5>
            <br>
            <p class="card-text">De R$560,00</p>
            <p class="card-text-1">Por R$420,00</p>
          </div>
        </a>
        </div>
        <div class="card" style="width: 18rem; padding: 20px; align-content: center;">
          <a class="link" href="{{url_for('product.water_cooler')}}">
          <img src="{{url_for('static', filename='assets/watercooler1.jpeg')}}" class="card-img-top" alt="Water Cooler">
          <div class="card-body">
            <h5 class="card-title">Water Cooler Corsair H150 RGB, 360mm, AMD/Intel, Preto - CW-9060054-WW</h5>
            <br>
            <p class="card-text">De R$820,00</p>
            <p class="card-text-1">Por R$640,00</p>
          </div>
        </a>
        </div>
        <div class="card" style="width: 18rem; padding: 20px; align-content: center;">
          <a class="link" href="{{url_for('product.fonte_for')}}">
          <img src="{{url_for('static', filename='assets/fonte1.jpeg')}}" class="card-img-top" alt="Fonte">
          <div class="card-body">
            <h5 class="card-title">Fonte Gamer Fortrek ATX Crusader, 500W, sem cabo, Preto - 76955</h5>
            <br>
            <p class="card-text">De R$140,00</p>
            <p class="card-text-1">Por R$100,00</p>
          </div>
        </a>
        </div>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Entrando</title>
  </head>
  <body>
  <form class="row g-3" style="margin-left: 30%; margin-right: 30%; margin-top: 100px;" action="{{url_for('client.singin')}}" method="POST">
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email</label>
        <input type="email" name="Email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Senha</label>
        <input type="password" name="Senha" class="form-control" id="exampleInputPassword1">
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Mantenha me conectado</label>
      </div>
      <button type="submit" class="btn btn-primary">Entrar</button>
      <a href="{{ url_for('client.singup')}}">Clique para se cadastrar</a>
  </form>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>